# Understanding NumPy for Numerical Data Analysis

NumPy (Numerical Python) is a fundamental package for numerical computation in Python. It provides support for large, multi-dimensional arrays and matrices, along with a collection of high-level mathematical functions to operate on these arrays. This notebook will demonstrate various essential functionalities of NumPy.

## 1. Importing NumPy

In [1]:
import numpy as np
print("NumPy imported successfully!")

NumPy imported successfully!


## 2. Creating Arrays

### 2.1. 1D Array

In [2]:
# Create a 1D array (vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(arr_1d)

1D Array:
[1 2 3 4 5]


### 2.2. 2D Array

In [3]:
# Create a 2D array (matrix)
arr_2d = np.array([[10, 11, 12],
                   [13, 14, 15],
                   [16, 17, 18]])
print("2D Array:")
print(arr_2d)

2D Array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]


### 2.3. 3D Array

In [4]:
# Create a 3D array
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6]],
                   [[7, 8, 9],
                    [10, 11, 12]]])
print("3D Array:")
print(arr_3d)

3D Array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 3. Array Attributes (Dimensions and Data Types)

In [5]:
print(f"arr_1d shape: {arr_1d.shape}, ndim: {arr_1d.ndim}, dtype: {arr_1d.dtype}, size: {arr_1d.size}")
print(f"arr_2d shape: {arr_2d.shape}, ndim: {arr_2d.ndim}, dtype: {arr_2d.dtype}, size: {arr_2d.size}")
print(f"arr_3d shape: {arr_3d.shape}, ndim: {arr_3d.ndim}, dtype: {arr_3d.dtype}, size: {arr_3d.size}")

# Change data type
arr_float = arr_1d.astype(np.float64)
print(f"arr_float dtype: {arr_float.dtype}")

arr_1d shape: (5,), ndim: 1, dtype: int64, size: 5
arr_2d shape: (3, 3), ndim: 2, dtype: int64, size: 9
arr_3d shape: (2, 2, 3), ndim: 3, dtype: int64, size: 12
arr_float dtype: float64


## 4. Indexing and Slicing

### 4.1. 1D Array Indexing and Slicing

In [6]:
print(f"arr_1d: {arr_1d}")
print(f"Element at index 0: {arr_1d[0]}")
print(f"Elements from index 1 to 3: {arr_1d[1:4]}")
print(f"Last element: {arr_1d[-1]}")

arr_1d: [1 2 3 4 5]
Element at index 0: 1
Elements from index 1 to 3: [2 3 4]
Last element: 5


### 4.2. 2D Array Indexing and Slicing

In [7]:
print(f"arr_2d:\n{arr_2d}")
print(f"Element at row 0, column 1: {arr_2d[0, 1]}")
print(f"First row: {arr_2d[0, :]}")
print(f"First column: {arr_2d[:, 0]}")
print(f"Sub-matrix (rows 0-1, cols 1-2):\n{arr_2d[0:2, 1:3]}")

arr_2d:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Element at row 0, column 1: 11
First row: [10 11 12]
First column: [10 13 16]
Sub-matrix (rows 0-1, cols 1-2):
[[11 12]
 [14 15]]


### 4.3. 3D Array Indexing and Slicing

In [8]:
print(f"arr_3d:\n{arr_3d}")
print(f"Element at depth 0, row 1, col 2: {arr_3d[0, 1, 2]}")
print(f"First slice (depth 0):\n{arr_3d[0, :, :]}")
print(f"All elements in the second column across all depths and rows:\n{arr_3d[:, :, 1]}")

arr_3d:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Element at depth 0, row 1, col 2: 6
First slice (depth 0):
[[1 2 3]
 [4 5 6]]
All elements in the second column across all depths and rows:
[[ 2  5]
 [ 8 11]]


## 5. Reshaping Arrays

In [9]:
print(f"Original arr_1d: {arr_1d}")
print(f"Reshaped to (5, 1):\n{arr_1d.reshape(5, 1)}")

print(f"\nOriginal arr_2d:\n{arr_2d}")
print(f"Reshaped to (1, 9): {arr_2d.reshape(1, 9)}")
print(f"Flattened arr_2d: {arr_2d.flatten()}") # Returns a copy
print(f"Ravelled arr_2d: {arr_2d.ravel()}") # Returns a view if possible

Original arr_1d: [1 2 3 4 5]
Reshaped to (5, 1):
[[1]
 [2]
 [3]
 [4]
 [5]]

Original arr_2d:
[[10 11 12]
 [13 14 15]
 [16 17 18]]
Reshaped to (1, 9): [[10 11 12 13 14 15 16 17 18]]
Flattened arr_2d: [10 11 12 13 14 15 16 17 18]
Ravelled arr_2d: [10 11 12 13 14 15 16 17 18]


## 6. Generating Arrays with Functions

### 6.1. `zeros()`

In [10]:
zeros_arr = np.zeros((3, 4))
print(f"Array of zeros:\n{zeros_arr}")

Array of zeros:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### 6.2. `ones()`

In [11]:
ones_arr = np.ones((2, 3), dtype=int)
print(f"Array of ones:\n{ones_arr}")

Array of ones:
[[1 1 1]
 [1 1 1]]


### 6.3. `full()`

In [12]:
full_arr = np.full((2, 2), 7)
print(f"Array filled with 7s:\n{full_arr}")

Array filled with 7s:
[[7 7]
 [7 7]]


### 6.4. `arange()`

In [13]:
range_arr = np.arange(0, 10, 2) # start, stop (exclusive), step
print(f"Array using arange: {range_arr}")

Array using arange: [0 2 4 6 8]


### 6.5. `linspace()`

In [14]:
linspace_arr = np.linspace(0, 1, 5) # start, stop (inclusive), number of points
print(f"Array using linspace: {linspace_arr}")

Array using linspace: [0.   0.25 0.5  0.75 1.  ]


### 6.6. Random Arrays

In [15]:
rand_arr = np.random.rand(2, 2) # Uniform distribution [0, 1)
print(f"Random array (rand):\n{rand_arr}")

randint_arr = np.random.randint(0, 10, size=(3, 3)) # Integers in [0, 10)
print(f"\nRandom integer array (randint):\n{randint_arr}")

Random array (rand):
[[0.41795392 0.08204761]
 [0.00319574 0.09874171]]

Random integer array (randint):
[[6 2 7]
 [6 3 8]
 [0 0 5]]


## 7. Mathematical and Vectorized Operations

In [16]:
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])

print(f"arr_a: {arr_a}")
print(f"arr_b: {arr_b}")

# Element-wise addition
print(f"\nAddition: {arr_a + arr_b}")

# Element-wise multiplication
print(f"Multiplication: {arr_a * arr_b}")

# Dot product
print(f"Dot Product: {np.dot(arr_a, arr_b)}")

# Universal functions (ufuncs)
print(f"Square root of arr_a: {np.sqrt(arr_a)}")
print(f"Exponential of arr_b: {np.exp(arr_b)}")
print(f"Sine of arr_a: {np.sin(arr_a)}")

arr_a: [1 2 3]
arr_b: [4 5 6]

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Dot Product: 32
Square root of arr_a: [1.         1.41421356 1.73205081]
Exponential of arr_b: [ 54.59815003 148.4131591  403.42879349]
Sine of arr_a: [0.84147098 0.90929743 0.14112001]


## 8. Boolean Masking

In [17]:
data = np.array([10, 25, 5, 30, 15, 20])
print(f"Original data: {data}")

# Create a boolean mask
mask = (data > 15)
print(f"Boolean mask (data > 15): {mask}")

# Apply the mask to filter elements
filtered_data = data[mask]
print(f"Filtered data (elements > 15): {filtered_data}")

# Another example: filter even numbers
even_numbers = data[data % 2 == 0]
print(f"Even numbers: {even_numbers}")

Original data: [10 25  5 30 15 20]
Boolean mask (data > 15): [False  True False  True False  True]
Filtered data (elements > 15): [25 30 20]
Even numbers: [10 30 20]


## 9. Broadcasting

In [18]:
arr_c = np.array([[1, 2, 3],
                  [4, 5, 6]])

scalar = 10
print(f"Array c:\n{arr_c}")
print(f"Scalar: {scalar}")

# Scalar-array broadcasting
print(f"\nArray c + scalar:\n{arr_c + scalar}")

# Array-array broadcasting (adding a 1D array to a 2D array)
arr_d = np.array([100, 200, 300])
print(f"\nArray d: {arr_d}")
print(f"Array c + Array d:\n{arr_c + arr_d}") # arr_d is broadcast across rows of arr_c

Array c:
[[1 2 3]
 [4 5 6]]
Scalar: 10

Array c + scalar:
[[11 12 13]
 [14 15 16]]

Array d: [100 200 300]
Array c + Array d:
[[101 202 303]
 [104 205 306]]


## 10. Common Aggregate Functions

In [19]:
agg_data = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(f"Data for aggregation:\n{agg_data}")

print(f"\nSum of all elements: {np.sum(agg_data)}")
print(f"Mean of all elements: {np.mean(agg_data)}")
print(f"Minimum of all elements: {np.min(agg_data)}")
print(f"Maximum of all elements: {np.max(agg_data)}")
print(f"Median of all elements: {np.median(agg_data)}")
print(f"Standard Deviation of all elements: {np.std(agg_data)}")

# Aggregating along an axis
print(f"\nSum along columns (axis=0): {np.sum(agg_data, axis=0)}")
print(f"Mean along rows (axis=1): {np.mean(agg_data, axis=1)}")
print(f"Index of minimum element: {np.argmin(agg_data)}") # Flat index
print(f"Index of maximum element: {np.argmax(agg_data)}") # Flat index

Data for aggregation:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of all elements: 45
Mean of all elements: 5.0
Minimum of all elements: 1
Maximum of all elements: 9
Median of all elements: 5.0
Standard Deviation of all elements: 2.581988897471611

Sum along columns (axis=0): [12 15 18]
Mean along rows (axis=1): [2. 5. 8.]
Index of minimum element: 0
Index of maximum element: 8
